config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :votes, dependent: :destroy
  has_many :candidates, dependent: :destroy
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :votes
  belongs_to :campaign

  validates_presence_of :name
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate
  belongs_to :campaign

  scope :valid, -> { where(validity: 'during') }
  scope :invalid, -> { where.not(validity: 'during') }
  scope :pre, -> { where(validity: 'pre') }
  scope :post, -> { where(validity: 'post') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @candidates = @campaign.candidates
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :campaign_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.title %></td>
        <td><%= link_to 'Details', campaign %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @campaign.title %>
</p>
<table>
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Votes</th>
      <th>Uncounted</th>
      <th>Pre</th>
      <th>Post</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.votes.valid.count %></td>
        <td><%= c.votes.invalid.count %></td>
        <td><%= c.votes.pre.count %></td>
        <td><%= c.votes.post.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', campaigns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mgager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>